### PR TITLE
Setup tests

### PR DESCRIPTION
**Pull request by slargman**
This pull request covers a lot of files, but what it aims to accomplish is to set up our testing environment, set up continuous integration, and layout the scaffolding for our project.

- Testing environment
  - This covers the jest installation changes in `package.json`, the jest configuration in `jest.config.js`
- Continuous integration
  - This will allow GitHub to automatically run our tests on a pull request and prevent merging if tests are failing. However, since we are all admins if this becomes annoying we can always force a merge regardless of any missing requirements such as failing tests or a missing code review.
  - `.github/workflows/test.yml` contains the script that GitHub will use for CI
- Project scaffolding
  - I wanted to set this up to make sure that our tests were working correctly. It also shows the test file structure we can choose to use: a `Component.test.js` file right next to `Component.jsx`. Jest automatically finds all these files when we run `npm test`. We can also set up jest in our script with the `--watch` flag to keep testing running in the background.
  - For end to end tests and integration test we might want to create a `tests` directory to contain these later
  - Added some linebreaks to `index.html`
  - I created aliases for our paths in `webpack.config.js`. This means that  instead of doing something like
  ```
  import App from '../../App/App.jsx';
  ```
  we can just do
  ```
  import App from 'App/App.jx';
  ```
  Aliases are set up for all the main component directories.
- .gitginore
  - I added some changes here as well
  - The main thing is we should not be tracking compiled files in our `client/dist` directory (i.e. `main.js`).
  - I also added the `coverage` directory. When you run `npm test` you will notice a new `coverage` directory which contains the coverage report from jest. This is an option I have enabled. We can turn off coverage reports if they're not wanted.

### CODE REVIEW

**Review by zman811 — COMMENTED** [review]
Looks great! really like the webpack alias to make it much easier to write.
Just a few questions I had, Did you add in the react testing library to test the page or will we do that later?

Also is there a reason to not git ignore package-lock.json?

**Comment by slargman** [comment]
Thank you for taking a look Zach. I don't think I added react testing library. It would just be an npm install later once we're writing tests. We would probably want to use it though since it provides helpers for our tests.

[According to the docs, `package-lock.json` is intended to be committed into source control to provide deterministic installs.](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json)

**Review by zman811 — APPROVED** [review]
Sweet! sounds good

**Comment by slargman** [comment]
I just checked and it seems like `react-testing-library` is installed.

**Comment by slargman** [comment]
Or at least installing it produced to changes in my repo.

**Comment by slargman** [comment]
@rlargman Don't know if you wanted to take a look at this just to get an idea of how we're laying out the app. There's no real code that's been committed yet, just a lot of infrastructure setup.

**Comment by rlargman** [comment]
Seems pretty standard 👍🏻

**Comment by slargman** [comment]
🧘

**Pull request merged**
