### PR TITLE
feat: make Carousel a controlled component

### PR DESCRIPTION
**Pull request by slargman**
Switches `Carousel` to follow a controlled component paradigm. The props `scrollIndex` and `onScroll` are used to achieve this.

`scrollIndex` tells `Carousel` the index of the first element from `items` that it should display. The number of subsequent items to be displayed is then determined by `size`.

The `onScroll` prop takes a function and is used to provide `Carousel` with an event handler that can inform the parent component of clicks to the buttons in `Carousel`. `Carousel` reports what `scrollIndex` should be to reflect the change represented by the button clicks by passing this value to the `onScroll` handler. That is, a button click triggers a call to `onScroll` with the argument `index`, where `index` reflects the value `scrollIndex` should take to reflect the button click.

These changes were necessary in order to enable the programmatic control of the `Carousel`, e.g. changes to `Carousel` that should be triggered by user interaction in a different component.

### CODE REVIEW

**Review by hangyin2020 — APPROVED** [review]
I kind of understand most of what is going on here, but I am still a little bit confused with what onScroll is doing, maybe I should play with it with my components for a while?

**Comment by slargman** [comment]
Sorry, I forgot to add a description to the PR. I'll edit one in now. Let me know if it clarifies things. Also did you take a look at the documentation for the props at the bottom of `Carousel.jsx`? I should improve it if it's not doing a good job of explaining things.

**Comment by hangyin2020** [comment]
> Sorry, I forgot to add a description to the PR. I'll edit one in now. Let me know if it clarifies things. Also did you take a look at the documentation for the props at the bottom of `Carousel.jsx`? I should improve it if it's not doing a good job of explaining things.

No worries about the description. I took a look at the prop types for onScroll if that is the documentation you are referring to, but not sure how to use it, I would probably refer to some of your code or play with it with my components. Don't worry too much about it

**Comment by hangyin2020** [comment]
that is very clear to me now, thanks! This code should be merged to the main but I did not see it there?

**Pull request merged**
