### PR TITLE
finish setting up fast refresh

### PR DESCRIPTION
**Pull request by hangyin2020**

### CODE REVIEW

**Comment by slargman** [comment]
Thanks for taking care of this Hang. I'm not seeing any changes to `package.json`. Do we need to install `react-refresh` and `react-refresh-webpack-plugin`?

**Comment by hangyin2020** [comment]
the article that I referred is here, I think I just did what the author said in an alternative way, please take a look https://javascript.plainenglish.io/react-fast-refresh-the-new-react-hot-reloader-652c6645548c

**Comment by slargman** [comment]
That article mentions installing those packages in the paragraph under the **Custom Webpack** heading. I'm not sure if things will work without the installation.

**Comment by hangyin2020** [comment]
I think you are right, let me try to add them to the package.json

**Review by slargman — APPROVED** [review]
Looks good. Thanks Hang!

**Pull request merged**
